#!/bin/bash

# arg1 is char nbr
# arg2 is line length

FILE=test.txt

echo -n 0 > $FILE
for (( i=1; i<$1; i++ )) do
	if [[ $((i%$2)) -eq 0 ]]; then
		echo -n $'\n' >> $FILE
	fi
	echo -n $((i%10)) >> $FILE
done
echo -n $'\0' >> $FILE
